quii/learn-go-with-tests

for/readme.md
for/v1/repeat.go
for/v1/repeat_test.go
for/v2/repeat.go
for/v2/repeat_test.go
for/vx/repeat.go
for/vx/repeat_test.go
integers/readme.md
integers/v1/adder.go
integers/v1/adder_test.go
integers/v2/adder.go
integers/v2/adder_test.go

`godoc` does not show any docs for files stored in `package main`. I've renamed the packages to how far I've gotten through this course, to match the chapters.
The docs will be generated with this change.

Change package name so godoc generates docs

---

integers.md

Note added mentioning that the presence of comment is important for execution of the example function.

Note added for exampe integer function

---

.mdlrc
.travis.yml
SUMMARY.md
arrays-and-slices.md
book.json
concurrency.md
contributing.md
dependency-injection.md
gb-readme.md
hello-world.md
http-server.md
install-go.md
integers.md
iteration.md
mocking.md
pointers-and-errors.md
select.md
structs-methods-and-interfaces.md
template.md

Hi @quii, Thank you for the great book!
With this PR, I introduced [MarkdownLint](https://github.com/markdownlint/markdownlint) to you. I add it to CI stage. When the doc style breaks the [rules](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md) the CI will fail([example](https://travis-ci.org/pityonline/learn-go-with-tests/jobs/372647823)), you may review what rules are used in `.mdlrc`.
It seems a lot of changes, but actually not that a lot, just trivial style matters. You may review it via `git diff --word-diff origin/master`.

add markdown lint, tidy doc style

---

integers.md

Beginners learning Go will be unfamiliar with the need to keep packages separate. A note in the second section aims to provide some guidance on this.
(it definitely tripped me up!)

Add early note about code structure

---

.travis.yml
README.md
install-go.md
mocking.md

* spelling check stage of CI will check all wrong spellings by [misspell](https://github.com/client9/misspell), even in documents.
* [Go Report Card](https://github.com/gojp/goreportcard) will generate a report on the quality of an open source go project. It has several checks with go toolchains, also a bundled misspell but only check the Go code without docs.
Because spelling check runs first on all files in CI, Go Report Card won't find any problem with it's bundled misspell.
Closes #9

add spelling check and Go Report Card

---

.gitignore

Just for keep a clean work directory after `gitbook serve`.

Chore: add _book/ to .gitignore

---

contributing.md

Small change to fix an empty link on the contributing page.
I've run `./build.sh` and it ✅ without issue.

Fix link to chapter template in contributing.md

---

install-go.md

Fix "evnironment" typo to "environment"

Fix "evnironment" typo to "environment"

---

structs-methods-and-interfaces.md

Following guidance from earlier in the doc the triangle receiver variable should be `t` instead of `c`.

Update triangle receiver variable

---

maps.md
maps/v2/dictionary.go
maps/v2/dictionary_test.go
maps/v3/dictionary.go
maps/v3/dictionary_test.go

Hey @hackeryarn 
I noticed after merging your PR that there were a number of `golint` warnings regarding the naming of your errors. 
In your chapter you start with the "bad" name and then refactor to the one prescribed by the linter. I would prefer it if we started with the correct way; assuming the user should be running golint as part of their development workflow (in practice, set it up in your IDE to always run)
There may be a need for us to emphasise this kind of setup earlier on in the book, but that can wait.
What do you think? If you're happy we can merge.

make the errors be golint friendly from the start

---

maps.md

It was pointed out in https://www.reddit.com/r/golang/comments/8w9cz6/learn_go_with_tests_maps/e1u9i04 that it was not actually a type alias. 
I modified the section to reference a custom type instead of a type alias.

removed type alias section

---

arrays-and-slices.md

The checkSums function was missing the t.Helper() method.

add the t.Helper() method

---

maps.md

Replace "test" with "unknown" as an input in test, when searching for an unknown word in the dictionary.

Fix a code mistake

---

maps.md

* replace `t.Error` with `t.Fatal`, so that the test stops, if we don't have an error;
* replace `got` with `err`, as `err` is the actual object we can call `Error()` on, here `got` is not defined

Fix a code snippet for failing test

---

integers.md

The extra 'in' in that sentence didn't feel right when reading it. Maybe it's possible to keep it and add a comma after it instead if you want.
I'll probably keep submitting these small changes to each chapter as I read them (if I find anything to change).

Add a missing space and remove a word

---

io.md
io/v4/FileSystemStore_test.go
io/v5/FileSystemStore_test.go
io/v6/FileSystemStore_test.go
io/v7/FileSystemStore_test.go
io/v8/FileSystemStore_test.go
io/v9/FileSystemStore_test.go

The test names in the IO section regarding testing `.RecordWin(...)` for new players has the test name `store wins for existing players` but should be `store wins for new players`.

Fix name of tests for recording wins of new players

---

.travis.yml

Hi, @quii, we don't have to pull the pandoc docker image during every CI stage. So I made it pull when necessary. Also, I formatted the style of .travis.yml, I think it would be better to read and maintain. Plz take a look at this. Thanks!

shorten CI build time, format .travis.yml

---

io.md

This is how it's named in later parts of the document as well as in
all the code examples

Rename `FileSystemStore` to `FileSystemPlayerStore`

---

io.md

We refactored database from `&tape{file}` to `json.NewEncoder(&tape{file})` earlier in this chapter

Fix typo in io code examples

---

maps.md

- Add the word "have".
- Remove "and get rid of the `given` piece", since it's not clear what `given` refers to.
- Add more context to Reference Types. It's not clear what is meant by "use". Now it's clear you can read from a nil map, but writes to a nil map cause a panic.
- Remove `**` from `Add**`, since it's inconsistent and not clear what it means.

Fix typos, grammar and add context info

---

time.md

The text says to update the code storing a `game` variable but we actually
need to call `PlayPoker()`. It seems the text would make more sense
listing the code needed to run the game.
See https://github.com/quii/learn-go-with-tests/blob/79ac957d0e4357d542e0f09c4a1c38e263b87d8a/time/v1/cmd/cli/main.go#L21

time.md - updating main code reference

---

time.md

It seems that `ReadString` should be `readLine` as there is no current
reference to `ReadString` in the code.
See https://github.com/quii/learn-go-with-tests/blob/79ac957d0e4357d542e0f09c4a1c38e263b87d8a/time/v1/CLI.go#L29

time.md errata - ReadString invalid code reference

---

gb-readme.md

Adding a link for the Github repo so it's immediately clear where to go from website to contribute

adding a link for the Github repo in gb-readme

---

hello-world.md
iteration.md

the const englishPrefix does not exist in the hello-world.md example and should be replaced with helloPrefix which does exist. 
I noticed in your actual hello-world go files that v8 does use englishPrefix, however. So, either this readme needs to be updated so that all instances of helloPrefix are replaced with englishPrefix or we simply replace the only instance of englishPrefix with helloPrefix, which is what I have done in the PR. 
P.S. This material is really great so far and I am learning a lot so thank you for making it!

replaced englishPrefix with helloPrefix in last refactoring example

---

reflection.md

When looking at the generated PDF I recognized, that the `golang challenge` quote had a hashtag which will be interpreted as a Header and so the ToC was wrong.

Remove wrong header

---

install-go.md

The `--cross-compile-common` flag is no longer supported.
It was removed by the following commit: https://github.com/Homebrew/homebrew-core/commit/bd56fd444ce3d21b647558d8740f6aade9180cba

Updates Go installation instructions

---

install-go.md

You no longer need to add a tap in order to use homebrew casks.

Updates VS Code installation instructions

---

hello-world.md

We can avoid a mistake by using `$GOPATH` instead of `~/go`, in case reader has set its path to be something else.

Updates mkdir to use $GOPATH

---

arrays-and-slices.md

I realize `go fmt` will catch this, so prob a minor change.

ln 475 - Added space before brackets

---

install-go.md

Go Meta Linter is deprecated and [about to be archived](https://github.com/alecthomas/gometalinter/issues/590). Replace with [GolangCI-Lint](https://github.com/golangci/golangci-lint)?

Replace deprecated Go Meta Linter with GolangCI-Lint

---

why.md

Fix the link to `Scala - Just enough rope to hang yourself` by prepending _www_ to the url

Fix Broken Link

---

structs-methods-and-interfaces.md

The [test](https://github.com/quii/learn-go-with-tests/blob/master/structs-methods-and-interfaces.md#write-the-test-first-1) for _circle_ area fails due to imprecise value of float64 Pi variable. This is already fixed in the solution code provided, but not reflected in the markdown documentation

Fix Failing Test due to imprecise value of Pi

---

install-go.md

go get -u github.com/derekparker/delve/cmd/dlv 
go get -u github.com/go-delve/delve/cmd/dlv

Debugger link can't go directly in install-go.md

---

command-line.md
command-line/v3/FileSystemStore.go
command-line/v3/cmd/cli/main.go
command-line/v3/cmd/webserver/main.go
time/v1/FileSystemStore.go
time/v1/cmd/cli/main.go
time/v2/FileSystemStore.go
time/v2/cmd/cli/main.go
time/v3/FileSystemStore.go
time/v3/cmd/cli/main.go
websockets/v1/FileSystemStore.go
websockets/v1/cmd/cli/main.go
websockets/v2/FileSystemStore.go
websockets/v2/cmd/cli/main.go

I noticed that `FileSystemStore` files were not being properly closed
I updated `FileSystemPlayerStoreFromFile` so that it returns a function that we can call to close the file it opened for us

close FileSystemStore file

---

.travis.yml

As an upstream, this repo depends on itself, but for a fork, it depends
on this repo. In Travis CI, `install: true` skipps `go get` for Go
projects, so the forks won't get the dependence and will cause the
CI failure. This is fixed by installing dependence in `before_install`.
Ref: https://docs.travis-ci.com/user/job-lifecycle/#skipping-the-installation-phase

fix CI for forks

---

select/v2/racer.go
select/v3/racer.go

Hello, when i read your graceful book *learn go with tests*, i found 
some issue in `select` chapter which will lead to goroutine leak.
If nobody receive from `ch`, this goroutine will always block, 
to avoid goroutine leak, we can make a buffered channel, like
`ch := make(chan bool, 1)` or just `close` it.
Also, i suggest use `done = make(chan struct{})`which more idiomatic in go
to substitute `ch := make(chan bool)` in this situation, thanks.

fix: avoid goroutine leak

---

hello-world.md

In the section introducing the French version of greeting prefix for the Hello World exercise, we use `"French"` but in the final overview section, it's written as `"french"`. This is a minor thing but I wanted to make sure the examples are consistent.

Capitalize French in arguments to Hello function

---

context.md

In the context exercise we update SpyStore to remove the cancel from the spy and just pass the context into the fetch. In one of the if statements of the happy path we reference store.ctx. 
Just removed the if statement to make the test actually run and pass like the instructions say.

Remove uncompilable if block from code example

---

arrays-and-slices.md

includes examples of slice reference and slice copy for better garbage collection

add go playground examples of array, slice & copy

---

pointers-and-errors.md

It took me a while crawling through the Go documentation to understand this black magic.

Make the struct pointer section more explicit

---

maps.md

Thanks for your great work! I was wondering if it made sense to add a full declaration to the empty map initialization examples for clarity.

Add var keyword to empty map initialization examples

---

mocking.md

Basically it read 'Print 3 to Go' and 'Print 1 to Go' was meant.
However, the current version is more clear IMHO.

The countdown's work divide was unclear

---

iteration.md

As `:=` has been used so far, it is explained briefly with a reference to examples.

Explain usage of `var`

---

structs-methods-and-interfaces.md

The sentence starts with "now", and then uses it again, referring to the same event. The second one can be deleted for clarity.

Remove redundant 'now'

---

context.md

We first create store in the following way:
`store := &SpyStore{response: data}`
and svr:
`svr := Server(store)`
Later, on lines 152 & 153:
`store := SpyStore{response: data}`
`svr := Server(&store)`
And from this point on, and defined in the files stored in the context folder in this repo:
`store := &SpyStore{response: data, t: t}`
`svr := Server(store)`
I believe for new members of this community trying to learn Go, it is best to keep it standard so people don't get confused, or change their code for unnecessary reasons.
My proposed change is to keep it in this way:
`store := &SpyStore{response: data}`
`svr := Server(store)`

Making store/svr creation in a standard way

---

mocking.md

Since the code sample is counting down, it is better to say `write a program which counts down from 3` rather than `write a program which counts from 3`

update text to make it more meaningful

---

hello-world.md

This helps one who has installed Go 1.1.3 which is no longer including `godoc` command. See #248

Add godoc note for 1.13 in hello world chapter

---

integers.md

The [hello-world.md](https://github.com/quii/learn-go-with-tests/blob/master/hello-world.md) file uses %q but then the next lecture [integers.md](https://github.com/quii/learn-go-with-tests/blob/master/iteration.md) references %s.
This pull request updates it to %q to be consistent with the first lecture.

Update integers.md to reference %q

---

install-go.md

Update help docs to include link to running Go debugger in VS Code. References #223

include link to VsCode-Go debugging help docs

---

maps.md

In the refactor we lose our nil check - should we not include this still?

Include nil check

---

http-server.md
http-server/v2/server.go
http-server/v3/server.go
http-server/v4/server.go
http-server/v5/server.go

Change all instances of `player := r.URL.Path[len("/players/"):]` to `player := strings.TrimPrefix(r.URL.Path, "/players/")`
using `strings.Trimspace` similarly to how the http package source code does it:
https://golang.org/src/net/http/server.go?#L2040

http-server: use strings.Trimspace instead of slicing

---

http-server.md

1. Improve explanations of the implementing the `http.Handler` interface for clarity.
2. Add documentation to match up with changes in the code with regards to mutex additions. Based on the following:
- https://github.com/quii/learn-go-with-tests/issues/238
- https://github.com/quii/learn-go-with-tests/pull/255

Fix documentation for http-server section

---

sync.md

There was a section of sync.md that was different from what go fmt would
output. This has been fixed.
Fixes #302

Fix formatting issue on sync.md

---

http-server/v5/InMemoryPlayerStore.go

Hi!
Thank you for your amazing book! I have learned a lot from it.
When I read the code in http-server/v5, I found the use of RWMutex was wrong. In the method `RecordWin()`，we need to modify the value of the store, so it should be unsafe in concurrency and use a write lock.  In the method `GetPlayerScore()`，we just read the data, so we can use a read lock. The situation was also mentioned in #297. I have fixed it now.

fix the wrong use of RWMutex in http-server/v5

---

install-go.md

I drafted a paragraph that mentions the usage of Go Modules and how someone can use them to work and run code outside of GOPATH. 
I think it's worth mentioning, since it will gradually become the 'proposed' way of working with Go projects, and it makes life easier. `go mod init` will create a couple of files, `go.mod` and `go.sum`, which hold information about packages and version requirements; I don't know if it should be mentioned as well.
Any comments on the writing style, the tone, or anything else are welcome.
Thanks!
Fixes : https://github.com/quii/learn-go-with-tests/issues/252

Mentioning Modules in the "Install Go" chapter

---

math.md

We can't turn Width and Height to float64 because in xml string there are values with '%' character and the test fails.

Math: SVG struct Width and Height

---

install-go.md

`<modulepath>`'s less-than/greater-than carets were getting rendered as an HTML tag, rendering them invisible in the final Markdown. This replaces them with the standard HTML. Happy to shift to backticks or another solution if preferred!
This is a documentation fix and shouldn't affect anything else.

fix formatting on modulepath to render it visible

---

time.md

I found that in time.md there is a NewReader in NewCLI, which causes compilation errors because the Reader does not have Text() or Scan() required in readLine(). In the code attached to time.md as I expected there is already NewScanner instead of NewReader, which has these methods and everything works correctly. I thought it's worth to change this small mistake in text.

replacement of NewReader with NewScanner in NewCLI(time.md)

---

install-go.md

The golangci-lint docs request not using `go get` to install; see https://github.com/golangci/golangci-lint/#go

Update command to install golangci-lint

---

reflection.md

This loop was previously removed in the chapter, and seems to has been
forgotten in the code blocks that comes after it.
The identation of those code blocks was also a bit wonky (mixing tabs and spaces) so I applied gofmt on it.
Closes #337

reflection: remove useless for loop

---

integers.md

Addresses issue #346 
- Replaced godoc.org by pkg.go.dev to be up to date with recent changes in terms of package documentation
- Added a brief description of what you can do thanks to this web interface

Fix: godoc.org was replaced with pkg.go.dev

---

io.md

To be consistent with the other error blocks.

Format error as code block

---

why.md

The renderer on https://quii.gitbook.io/learn-go-with-tests/meta/why cannot handle `))`
unlike Github's renderer.
Thus currently the https://quii.gitbook.io/learn-go-with-tests/meta/why looks broken.

fix Manny Lehman link on gitbook.io

---

arrays-and-slices.md
command-line.md
concurrency.md
dependency-injection.md
error-types.md
hello-world.md
http-handlers-revisited.md
http-server.md
integers.md
iteration.md
json.md
select.md

Hello
First thanks for this very good guide. I saw that sometimes the code displayed had style that do not follow `go fmt`, like `[]int{1,2}, []int{0,9}`
I used [gofmtmd](https://github.com/po3rin/gofmtmd) package:
```sh
ls -1 *.md  | xargs -I % sh -c 'echo %; gofmtmd % -r'
```
There is some errors, in file that could not be parsed. So this is a partial fix to formating markdown file.
No problem to refuse this PR if you think this is not important.

go fmt code block to reduce formating issues

---

mocking.md

Noticed a couple of people have asked you about this on twitter, think a small explainer should be added to the Mocks chapter.

Add explanation on absence of mock generators

---

select.md

Hi all,
I've been following this repo to help teach myself go and it's been a great help.
I noticed on line 399 the first argument in t.Run doesn't match the assertion. Raising this PR for your consideration as to whether you think this wording fits better or not.

Reword test block to better match assertion

---

hello-world.md

Consistently refer to file created as hello.go.
Fixes #390

Fix typo in hello world

---

mocking.md

Removing the word "do" from "in theory you should be able to do make the commit without any test changes."  makes more grammatical sense.

Typo in mocking.md

---

context.md

Latest implementation (v3) using TestServer instead of TestHandler

Rename TestHandler to TestServer

---

pointers-and-errors.md

You've been using the startingBalance variable in the code examples and it feels inconsistent to stop using it in the middle.
So it goes in the following order:
```
t.Run("Withdraw insufficient funds", func(t *testing.T) {
startingBalance := Bitcoin(20)
wallet := Wallet{startingBalance}
err := wallet.Withdraw(Bitcoin(100))
assertBalance(t, wallet, startingBalance)
if err == nil {
t.Error("wanted an error but didn't get one")
}
})
```
Then:
```
t.Run("Withdraw insufficient funds", func(t *testing.T) {
wallet := Wallet{Bitcoin(20)}
err := wallet.Withdraw(Bitcoin(100))
assertBalance(t, wallet, Bitcoin(20))
assertError(t, err)
})
```
And then again:
```
t.Run("Withdraw insufficient funds", func(t *testing.T) {
startingBalance := Bitcoin(20)
wallet := Wallet{startingBalance}
err := …
```

Inconsistency in usage of the startingBalance variable in pointers-and-errors.md

---

concurrency.md
concurrency/v3/check_websites.go

Going through this for the first time and being new go Go I found I found it a little odd that we are using the same name as the type, for the variable assignment. Naming is hard and maybe `r` is not great either, wdyt?

Using a different name for the result variable assignment

---

gb-readme.md

On https://quii.gitbook.io/learn-go-with-tests/ the two separate bulleted lists (translations and book description) are rendered as a single list:

Move some text to improve readability

---

hello-world.md

I noticed when working through the Hello World page that the reader is instructed to try commenting out a line of their code before the concept of code comments was introduced. This change adds a little intro just after its use to provide guidance.
Also noticed that the section talking about zero values the the int type code highlighted but not the immediately following reference to string. If that was intentional, I can revert that real quick.

Brief intro to comments and tiny formatting update.

---

hello-world.md

This is a quick pass at including information about Go modules. I kept
things very brief, but this should allow people on Go 1.16 (or later) to
continue with the tutorial.
I mentioned that people should run `go mod init` in all future folders,
but perhaps it would be kinder to add that command to all subsequent
chapters? I couldn't decide, but this is a start.
Thanks again for the book!

Add information about Go modules

---

install-go.md

* clarify that go modules are now the default
* update the example with what `go mod init cmd` would create with go 1.16

Update Go module section according to Go 1.16

---

context.md
context/v2/testdoubles.go

Thanks so much for this fantastic book. I've really enjoyed it.
I noticed a couple of discrepancies in the Context chapter and I've proposed some changes. Please feel free to let me know if they are invalid changes.
In two instances, `t.Errorf` was being called even though there were no
formatting 'verbs' in the specified errors. They have been replacd with
t.Error in the code snippets in the markdown files as well as the
accompanying code.

Use t.Error where appropriate in Context section

---

roman-numerals.md
roman-numerals/v10/roman_numerals.go
roman-numerals/v11/roman_numerals.go

The provided code contained an unneeded cast of a `byte` to a `byte` the `windowedRoman.Symbols` function. This cast has been removed in these changes both in the markdown and in the relevant source code files.
This PR also contains a markdown source reformat of the symbols table in the roman numerals/property test write up.

Remove unneeded byte cast in roman numerals code

---

command-line/v3/file_system_store.go

If the game db file is corrupt, then it can be opened successfully but parsing the league from it will fail. In this situation `FileSystemPlayerStoreFromFile` wouldn't close the db file.
I have added `db.Close()` into the second error handling block to cure this issue.

fix(command-line): close db if it cannot be parsed

---

math.md

The unit circle picture that is provided in
<https://quii.gitbook.io/learn-go-with-tests/go-fundamentals/math#write-enough-code-to-make-it-pass-3>
is the standard unit circle which measures angles from the X axis
instead of the Y axis. This may cause readers to use cosine when
calculating X and sin when calculating Y instead of the other way
around. This change adds the image in which the triangle is flipped and
the angle is measured from the Y axis (12 o'clock) and in which X is
clearly shown as sin(α) and Y is shown as cos(α)

Add clarifying image above secondHandPoint in math

---

command-line.md
command-line/v2/CLI_test.go

On line 9 of the `CLI_test.go` code snippet in
https://quii.gitbook.io/learn-go-with-tests/build-an-application/command-line#write-the-test-first-1
`playerstore.winCalls` is checked if it is less than 1 `< 1` whereas on
line 11 of the `CLI_test.go` code snippet in
https://quii.gitbook.io/learn-go-with-tests/build-an-application/command-line#write-the-test-first
`playerstore.winCalls` is checked if it is not-equal to 1 `!= 1` and
similarly on line 5 of the `server_test.go` code snippet in
https://quii.gitbook.io/learn-go-with-tests/build-an-application/command-line#refactor
`store.winCalls` is checked if it is not-equal to 1 `!= 1`
This change makes the `playerstore.winCalls` length check on line 9 of
the `CLI_test.go` code snippet in …

Make len checks consistent in command-line tests

---

reflection.md
reflection/v10/reflection.go
reflection/v9/reflection.go

I think this change works. go test still passes.﻿
Thanks for the book, I'm enjoying working through it.

reflection: Use walkValue to match other branches in switch

---

maps.md

Hello, 
I noticed the error message from go did not match the one in maps.md. I have corrected that with this small pull request.
Side note: Thanks again for making this tutorial. This is my second time through it and I am still learning so much.

corrected error message during TestUpdate in maps

---

hello-world.md

Given the context, I believe the text should say "make it compile". The test will not pass at this point.

Fix small typo

---

mocking.md
mocking/v4/countdown_test.go
mocking/v5/countdown_test.go

purpose of rename is to add consistency between all Spies introduced in the chapter #487

-renamed CountdownOperationsSpy

---

pointers-and-errors.md

`type declaration` is not the same as `type aliasing`.
`type aliasing` is the same as the original type you alias but with a different name.
`type declaration` (aka `type branding`) is taking another type and creating a *completely new type* that "extends" the original type.
https://golang.org/ref/spec#Type_declarations
The type declaration which was used in the guide will make compile errors if we try to pass something that is not `untyped const` or the declared type (Bitcoin) to it.

fixing small mistake in explanation

---

arrays-and-slices.md

fix: Add description regarding an error learner might encounter when he/she/they initialize go mod with name of main by looking at the package name in source code

fix: Add description regarding an error learner might encounter

---

websockets.md

The cctual filename is https://github.com/quii/learn-go-with-tests/blob/main/websockets/v2/blind_alerter.go
`BlindAlerter.go` -> `blind_alerter.go`

Fix file name BlindAlerter.go to blind_alerter.go in websockets.md

---

select.md

http://www.quii.co.uk is not your domain anymore (and makes the first test fail because it's slower than http://www.facebook.com)

Replace quii.co.uk with quii.dev

---

context-aware-reader.md

Add "'" to "dont" in context-aware-reader.md

---

html-templates.md

Fixes a broken link to [gomarkdown](https://github.com/gomarkdown/markdown) in the recently added templates chapter.

fix: broken gomarkdown link

---

io.md

In the flow of the text the code for the function assertScoreEquals(t, got, want) is omitted. This causes the examples to not work.
I've fished it out of the code and popped it into the text.

Adding refactoring that was omitted from text

---

io.md

As this is the second assignment of got in this function, := is improper and '=' should be used.

Minor bugfix (wrong operator)

---

integers.md

I saw #434 and #399 had intention to remove GOPATH related comments in this book (This is a great book, by the way) so this sentence should be considered differently. That's why I opened this pull request.
And this chapter might need to explain how the packages have docs on `http://localhost:6060/pkg` and how the `adder` example gets there,  when the reader doesn't have GOPATH set up

Remove GOPATH related comments

---

hello-world.md

why this change: an error message was raised when I followed current doc
```
go get: installing executables with 'go get' in module mode is deprecated.
To adjust and download dependencies of the current module, use 'go get -d'.
To install using requirements of the current module, use 'go install'.
To install ignoring the current module, use 'go install' with a version,
like 'go install example.com/cmd@latest'.
For more information, see https://golang.org/doc/go-get-install-deprecation
or run 'go help get' or 'go help install'.
```

Use `go install` for installing `godoc` executable

---

pointers-and-errors.md

https://go.dev/doc/go1.18
Now that go 1.18 has been released, I think it's a good opportunity to unify the description to go install

migrate `go get` to `go install` in `pointers-and-errors.md`

---

generics.md

Fixes compilation error: 
`(*testing.common).Errorf call needs 1 arg but has 2 args`

Add missing format directive to t.Errorf() call

---

generics.md

This fixes an example in generics.md where the arg count doesn't match the pattern.

Fix a generics example

---

reflection.md

The inclusion of `any` in Go 1.18 was controversial, but since it's here we might as well mention it briefly

📝 Add note about `any`

---

pointers-and-errors.md
pointers/v2/wallet_test.go
pointers/v3/wallet_test.go
pointers/v4/wallet_test.go

The project already using no capitalization for the subtest names, so this commit aims to fix that for the "Pointer and errors" chapter(and .go files).

fixed capitalization of subtest names

---

io.md

Small typo in the text, written "string.NewReader" when we want
"strings.NewReader"
Issue(s): None

Fix typo - strings.NewReader

---

concurrency.md
concurrency/v1/check_websites_test.go
concurrency/v2/check_websites_test.go
concurrency/v3/check_websites_test.go

Made test error messages to start with lowercase(in "Concurrency" chapter and it's *.go files), so it follows the rest of the project.

fixed: test error messages should be lowercase

---

time.md

Fix the casing on `BlindAlerter.go` to be consistent with the rest of the file names.
When comparing with https://github.com/quii/learn-go-with-tests/tree/main/time/v1 the filename should be snake case instead.
---
Also, big thanks for creating this book, I'm learning a lot while working through it! 🚀

Change filename to blind_alerter.go

---

websockets.md

Minor fix to the syntax highlighting to make it consistent with the rest of the page.

Fix syntax highlighting for blind_alerter.go

---

generics.md

Changed 4 spaces indentation to tabs as it was rendered incorrectly before
Before:

change spaces to tabs in generics.md

---

command-line.md
math.md
reflection.md

In [2020](https://go.dev/blog/pkg.go.dev-2020) godoc.org has been migrated to pkg.go.dev.

godoc.org is now pkg.go.dev

---

math.md

[`Unmarshal`](https://pkg.go.dev/encoding/xml#Unmarshal) has with one 'l'.

Fix typo in xml.Unmarshal

---

roman-numerals.md

If you just copy as is, go compiler will complain about the missing comma at the end. Fixed.

Added comma for easier copy paste

---

SUMMARY.md
intro-to-generics.md

There's no reason to keep the empty chapter, it got moved to Go fundamentals after Go 1.18 released.

Removed "Intro to generics" chapter

---

install-go.md

A few small changes:
* Add a link to https://awesome-go.com using Markdown link style - I noticed I couldn't click through to the site from [the docs built here](https://quii.gitbook.io/learn-go-with-tests/go-fundamentals/install-go)
* Format bullet points on page consistency: Period at the end of the bolded section. Period at the end of each sentence.
* Cut a few words that seemed unnecessary.

Minor tweaks to Install Go page

---

dependency-injection.md

I'm running the latest mac os (12.3.1) and I'm not able to start the server with port 5000. It seems like a mac os system app called ControlCentre is using that port so to avoid unnecessary issues I think switching port might be a good idea.
I run these commands to check what's running on port 5000
```
lsof -i -P | grep -i "5000"
```
output
```
ControlCe 98168 trondfroding   19u  IPv4 0x7d09d3228c03ccf3      0t0  TCP *:5000 (LISTEN)
ControlCe 98168 trondfroding   20u  IPv6 0x7d09d31da622b6fb      0t0  TCP *:5000 (LISTEN)
```
when grepping for the those process ids `ps -ef | grep 98168` i get this output
```
501 98168     1   0  9:41PM ??         0:01.04 /System/Library/CoreServices/ControlCenter.app/Contents/MacOS/ControlCenter
501 98212 96133   0  9:42PM ttys013    0:00.00 grep 98168
``` …

Avoid mac os port conflict

---

command-line/v1/server_test.go
command-line/v2/server_test.go
command-line/v3/server_test.go
io/v1/server_test.go
io/v2/server_test.go
io/v3/server_test.go
io/v4/server_test.go
io/v5/server_test.go
io/v6/server_test.go
io/v7/server_test.go
io/v8/server_test.go
io/v9/server_test.go
time/v1/server_test.go
time/v2/server_test.go
time/v3/server_test.go
websockets/v1/server_test.go
websockets/v2/server_test.go

Some of the test code still used `HeaderMap` in their assertions, even tho in the *.md files it's fixed: https://github.com/quii/learn-go-with-tests/blob/a9d05d3511ad2373a166886bf0bcd80a05a61dac/json.md?plain=1#L653

Replaced HeaderMap as it's deprecated

---

mocking.md
mocking/v3/countdown_test.go
mocking/v3/main.go
mocking/v4/countdown_test.go
mocking/v4/main.go
mocking/v5/countdown_test.go
mocking/v5/main.go

Changed tests and `main` codes in `mocking/v3/ - v5/` to only call `sleeper.Sleep()` between the prints.  
While editing `mocking.md`, I also made a few grammar corrections there, hope you don't mind. :v: 
Closes:  #583

Removed redundant Sleep() in Mocking

---

error-types.md

It seems that they were using underscores for URL sections and now they are using hyphens.

Fix link to "errors.As" example in Error types section

---

http-server.md

As stated in Issue #596, I have fixed the example.

Updated code example to fit previous refactor

---

structs/v8/shapes.go

From [the chapter description](https://quii.gitbook.io/learn-go-with-tests/go-fundamentals/structs-methods-and-interfaces#write-the-minimal-amount-of-code-for-the-test-to-run-and-check-the-failing-test-output-2), it suggests using the first letter of the receiver type as a receiver variable.
Therefore, I slightly changed receiver variable letters from c to t (since type is Triangle) in structs/v8/shapes.go.
Thanks!

Fix typo on receiver variables from `struct` example

---

arrays-and-slices.md

The first code example showing the shape of the `SumAll()` function has a named return value in it of `(sum []int)` where later examples drop the named return value. If learners are not careful and notice the change, they may overlook the different return signature and get surprised by a `NoNewVar` error later on in the process when `sum := ...` is written.
https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#NoNewVar
This changes the initial entry to line up with the rest of the examples in the document.

fix: Consistent example code for SumAll() example

---

generics.md
reflection.md

Based on the context, I think in these places by `interface` the author actually meant `interface{}`. This PR fixes this typo to avoid confusion.

Fix typo around `interface{}`

---

maps.md

The use of spaces is currently causing the generated html code to be misaligned.

maps.md: use tabs in code example

---

math.md

In first code demo, it import "github.com/gypsydave5/learn-go-with-tests/math/v1/clockface". But learner need create clockface.go by themself and that import cause confusing

Remove confuse import in clockface test

---

maps/v7/dictionary_test.go

Updating TestDelete to use `assertError(t, err, ErrNotFound)` so it is consistent with the rest of the tests.

use assertError for TestDelete

---

generics.md
mocking.md
reflection.md
select.md
sync.md

👋 Hello - thanks for maintaining `learn-go-with-tests`. This PR seeks to make a few tweaks...
* properly format the markdown blockquote and link at https://quii.gitbook.io/learn-go-with-tests/go-fundamentals/mocking#mocking-1
* fine tune some language to be a bit more clear
* include previously missing commas and periods
* correctly use the two word verb phrase "clean up" rather than the one-word noun ("cleanup")
* correct comma placement
If I'm not mistaken, there are a number of other similar grammar and spelling errors throughout `learn-go-with-tests` too. I've attempted to keep this PR relatively-ish small and easy to review, but if you're receptive to the changes, I'm happy to continue opening similar follow-on PRs (or to add additional commits to this PR, if you prefer).

Fine tune language, punctuation, and markdown formatting

---

scaling-acceptance-tests.md

As I was going through [Scaling acceptance tests](https://quii.gitbook.io/learn-go-with-tests/testing-fundamentals/scaling-acceptance-tests), I updated the code sample imports and tree structures to reflect the current state the code seemed to be in.

Fix: corrected imports in code samples; corrected tree structures

---

intro-to-acceptance-tests.md

Hi.
There's a broken link in intro-to-acceptance-tests.md file.
I fixed it.
All tests passed and I didn't change styling.
Thanks!

Fix typo (broken link) in markdown for intro-to-acceptance-tests

---

math.md

The function name seems wrong in this part of the document, TestSecondHandPoint is used further in the document and is testing secondHandPoint.

Fixes typo in test name

---

maps.md

func `assertStrings` already exists why not use it?

Use `assertStrings` in `maps.md`

---

html-templates.md

Hi, thanks for your awesome learning materials!
I found and fixed a small typo in **Templating** when I've translated to Japanese it.
- https://github.com/andmorefine/learn-go-with-tests/pull/25
Thank you.

Fix typo in html-templates.md

---

hello-world.md

We were refactoring the subtest helper method while one subtest was still failing. I've moved the refactor down so we fix the failing test first, then refactor.

Move test refactoring to after tests pass

---

hello-world.md

cases in the switch statement would be unrecognised types, I've changed them to strings as used in the params.

Fix type in switch case examples

---

generics.md

As the explanation says the assert should fail and that the output message would be `got 1, want 1`, the tried comparison should be done with the AssertEqual() function instead of AssertNotEqual().

Fix assert when comparing two different types

---

reflection.md

swapping references to abstract words foo bar etc to words with inherent context around them

Change Foo Bar

---

reflection.md

Includes instructions to check the error message after refactoring maps assertions from the table test into its own test with helper

Check error message for new test

---

scaling-acceptance-tests.md

The import package name is different from the module name.

Fix specifications package import

---

hello-world.md

Fixes switch statement example from [hello-world.md](https://github.com/quii/learn-go-with-tests/blob/main/hello-world.md#switch).
Right now switch cases are non capitalized which will lead to failed tests, code expects language string like "French" and not "french". That mistake not covered in book, so I assume it's just a mistake and not an example of any sort.

fix: hello-world.md in switch cases language starts with capital letter

---

math.md

I've removed Dave and Chris' usernames from the project references so that any mention of the project path is a bit cleaner, eg. in quoted failure messages it will read learn-go-with-tests/math/clockface

tidy up project references

---

math.md

- Any links like https://github.com/quii/learn-go-with-tests/blob/main/math/v7c/clockface (`blob`) were auto directing to a non-existant README.md resulting in a 404
- they are replaced with https://github.com/quii/learn-go-with-tests/tree/main/math/v7c/clockface (`tree`) which expects to open the file tree

Fix links to code examples in repo

---

select.md

In the Select chapter, after adding the `error` in the return from `Racer` we need to also update our original test to handle the error, else when we run the tests we will see:
```sh
/racer_test.go:24:16: assignment mismatch: 1 variable but Racer returns 2 values
```
Given we do nothing with it until later on, handling with `_` makes the most sense.
I've included the initial test in full to demonstrate the change, and added a note for the reader to explain why this change needs to be made.

Handle the error returned by our updated Racer function

---

generics.md

- Update the test description to `DX` instead of `dx`
- Add the missing `t` arg for the `AssertEqual` helper's first param

Change description and args for testing interface stack in generics.md

---

math.md

A section of the math chapter says to add an Svg struct to a `clockface_assembly_test` file, but that's not the name of a test file that's used in the clockface example. Because the next state of the code (v7b) shows that struct (and the corresponding code) in the `clockface_acceptance_test` file, this MR updates the name of the mentioned test file from `clockface_assembly_test` to `clockface_acceptance_test`.

fix(math): clarify which test file to use

---

reflection.md

According to the source of Go, Pointer is the new name for the pointer kind.

Update reflection.md to use Pointer instead of Ptr

---

select.md

The error is handled properly [a little bit after](https://github.com/quii/learn-go-with-tests/blob/main/select.md?plain=1#L416) in the document

at this stage we purposely ignore error with blank identifier

---

reflection.md
reflection/v10/reflection_test.go
reflection/v8/reflection_test.go
reflection/v9/reflection_test.go

Removes unnecessary + flag from format string, it doesn't affect output for slices.

remove unnecessary plus flag for slice output format

---

build.books.sh

Replace use of older `uppalabharath/pandoc-latex-cjk:latest` image with `pandoc/latex:edge-ubuntu`.
At present the older image is from November 2021 and contains Pandoc 2.16.1, whereas the `pandoc/latex:edge-ubuntu` image is from March 2023 and provides Pandoc 3.1.1.
epub files generated using this newer image successfully import into Google Play Books without error.
- GH-598

Use current pandoc/latex image to generate epub

---

anti-patterns.md

I think the problem of the so-called "interface pollution" is crucial for the language and it should be mentioned in this resource. I wrote a small section describing the issue with a link to a rakyll's blog post.

proposal: add a paragraph about interface pollution in the anti-patterns section

---

build.sh
command-line.md
generics.md
hello-world.md
html-templates.md
http-server.md
intro-to-acceptance-tests.md
io.md
math.md
reflection.md
roman-numerals.md
scaling-acceptance-tests.md
select.md
working-without-mocks.md

This PR enables `misspell` and `gofmtmd` linters in the `build.sh`. Also, formats md-files.
`golint` is deprecated. So, no need to enable it.

Enable misspell and gofmtmd; fix formatting issues

---

build.sh

Because `github.com/gorilla/websocket` already present in the [go.mod](https://github.com/quii/learn-go-with-tests/blob/main/go.mod).

build.sh: remove unnecessary go get and resolve TODO

---

pointers-and-errors.md

After the Stringer interface is implemented `%v` will no longer print the memory address but instead will invoke the Stringer interface which is confusing. 
Using `%p` means it will consistently print the variable's memory address.

Use `%p` to print &wallet.Balance in pointers-and-errors.md

---

arrays-and-slices.md

Added a line telling about the new "slices" package available from Go 1.21 which has slices.Equal, and that it has no issues with type

Update arrays-and-slices.md - added slices package tip

---

arrays-and-slices.md

Added line to explain that the slices.Equal function expects the slice elements to be comparable
Ref: https://github.com/quii/learn-go-with-tests/pull/722#issuecomment-1862422513

Update arrays-and-slices.md: Improved slices package tip with comparable

---

roman-numerals.md
roman-numerals/v10/roman_numerals.go
roman-numerals/v11/roman_numerals.go

I think that your version of the conversion of roman numbers back to arabic numbers is too complicated, and distracts a bit from the main focus, the following property testing topic.
I've taken the `ConvertToRoman(int)` algorithm using it backwards, basically. I've updated the markdown accordingly and let my wife audit the text as her english is better than mine. But I deleted a lot of your previous tests and text of the complicated  algorithm you implemented. I hope you don't mind. There might now be a gap between the test for `ConvertToArabic("IV")` and the final version, but I don't know how to fill it. Maybe it's not even a problem, cause there were many test steps ahead of it already.

Simplified ConvertToArabic algorithm

---

roman-numerals.md

It's only introduced later in the text.
The tests at the current stage all expect int.

roman-numberals.md: Don't use uint16 too early

---

websockets/v1/vendor/github.com/gorilla/websocket/README.md
websockets/v2/vendor/github.com/gorilla/websocket/README.md

In relation to: https://github.com/quii/learn-go-with-tests/issues/691

Update godoc links with their respective pkg.go.dev equivalents

---

scaling-acceptance-tests.md

While reading [Scaling acceptance tests](https://quii.gitbook.io/learn-go-with-tests/testing-fundamentals/scaling-acceptance-tests), I tried building a docker image using the `Dockerfile` as the one in the book and failed to do so. 
Then I realized I was using Go version >= 1.22.0 on my machine and that was the main problem.
Although I don't think it would be a good idea to change the Go version used in the book(because everyone has her/his own favorite Go version), I think at least it would be good to mention it so that a reader could modify her/his own `Dockerfile` with the Go version installed on her/his machine.

specify go version in Dockerfile

---

select.md

In the previous section, an error return was added to the `Racer()` function. In the text underneath this code block there is a note on [line 267](https://github.com/quii/learn-go-with-tests/compare/main...kevinlangmade:learn-go-with-tests:patch-1#diff-f3a62cc6403b42fe6683357a1b8dd83ef30d121c327702566b5d3dc4869a3f55L297) that says:
> Note that we've also handled the error return in our original text, we're using `_` for now to ensure the tests will run.
I think the error was not actually ignored with an underscore as you intended.

Correct syntax error in select.md

---

intro-to-acceptance-tests.md

While I was reading the chapter ["Introduction to acceptance tests"](https://quii.gitbook.io/learn-go-with-tests/testing-fundamentals/intro-to-acceptance-tests#how-to-write-basic-acceptance-tests) with actual coding, I found the following missing part:
According to example code of [Graceful shutdown decorator package](https://pkg.go.dev/github.com/quii/go-graceful-shutdown#section-readme), I would like to suggest the same code example in the book as well:
```go
func main() {
var (
ctx        = context.Background()
httpServer = &http.Server{Addr: ":8080", Handler: http.HandlerFunc(acceptancetests.SlowHandler)}
server     = gracefulshutdown.NewServer(httpServer)
)
// code omitted
}
```

Add missing ctx variable in the func main() in the "introduction to acceptance tests" chapter

---

integers.md

I wanted to distinguish Go's "Testable Examples" as something more than "examples".
`./build.sh`  ran OK:
```
$ ./build.sh
go: downloading github.com/client9/misspell v0.3.4
go: downloading github.com/po3rin/gofmtmd v0.1.3
go: downloading github.com/spf13/cobra v0.0.5
go: downloading gopkg.in/russross/blackfriday.v2 v2.0.0
go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0
go: downloading github.com/spf13/pflag v1.0.3
formatting  file: ./LICENSE.md
formatting  file: ./README.md
formatting  file: ./SUMMARY.md
formatting  file: ./anti-patterns.md
formatting  file: ./app-intro.md
formatting  file: ./arrays-and-slices.md
formatting  file: ./command-line.md
formatting  file: ./concurrency.md
formatting  file: ./context-aware-reader.md
formatting  file: ./context.md
formatting …
```

docs: examples --> Testable Examples

---

hello-world.md
hello-world/v7/hello.go

it's a very minor improvement but I thought I might as well open a PR for it :slightly_smiling_face: 
basically this PR does two things in regards to the hello example:
- reorder the places in which french is placed before spanish
(to improve consistency, as currently spanish is sometimes before french and sometimes after)
- in the language prefix switch use variables instead of string literals since those are already defined in the guide

in the hello example, reorder spanish and french and use variables in switch statement

---

context.md

Corrects a typo in the opening passage from `stub` to `spy` to properly reflect the code in the rest of the chapter.
Fixes #756

fix stub typo to spy in Context chapter

---

maps.md
maps/v1/dictionary_test.go

The `assertError` in the maps section is introduced here:
https://github.com/quii/learn-go-with-tests/blob/7c5b39c9c0182b53c9e2c0a892f52252a3592d62/maps.md?plain=1#L222-L228
as you can see with the failure error being `got error "X" want "Y"`
This does not match the v1 go code: https://github.com/quii/learn-go-with-tests/blob/7c5b39c9c0182b53c9e2c0a892f52252a3592d62/maps/v1/dictionary_test.go#L18
Further down the section the `assertError` helper is refactored:
https://github.com/quii/learn-go-with-tests/blob/7c5b39c9c0182b53c9e2c0a892f52252a3592d62/maps.md?plain=1#L367-L375
to update the failure error to `got "X" want "Y"` (without `error`)
This does not really make much sense and is also not reflected anywhere in the section's go code (see: …

fix: fix inconsistent definition of `assertError` function in maps section

---

html-templates.md
os-exec.md

Fix the dependency injection links pointing to `/dependency-injection.md` instead of `./dependency-injection.md`
Although this absolute links do work in the gitbook site they don't work in the EPUB and PDF versions

fix incorrect incorrect local links to the dependency injection section

---

maps.md
pointers-and-errors.md

The `.Error()` method is used in the pointers and errors section without an explanation, and is then explained in the maps section (which comes after the pointers and errors one).
The changes here are reordering this so that readers get the explanation in the pointers and errors section.

fix the incorrect order of explanation of the `.Error()` method

---

pointers-and-errors.md

closes #711
:point_up: hopefully this should be enough to close #711 given the fact that #616 has already been merged

explain what the `%p` placeholder prints

---

maps.md

Updates maps.md to outline that nil maps should not be created but rather empty ones or by using the make function.

Updates maps.md to outline that nil maps should not be created

---

maps.md

The previous tests from maps was using `assertError` but this one doesn't

refactor: using assertError function on TestDelete of maps section

---

maps.md

The variable name being passed as parameter to assertStrings function should be `definition`.

fix(maps): update var name

---

maps.md

otherwise the refactor contains a regression

make func TestSearch.unknown_word check for nil

---

arrays-and-slices.md

This PR gives a two line explanation about length and capacity in slices and two different  ways to declare slices and their difference in 'arrays-and-slices.md'.
Solving issue  slice length and capacity #577

Added little explanation about length and capacity of slices 

---

maps.md

Fixing a few typos I've found in the `Maps` chapter.

fix: typos in the chapter about maps

---

mocking.md

One execution of `sleeper.Sleep()` was missing in the code example.

fix: mocking code exemple

---

arrays-and-slices.md

Whitespace has been missing between the sentences since a6c085db36f137cc37b6bba08f908aa8c4e7f14d .

fix: add missing whitespace

---

integers.md

This pull request updates the documentation examples to use "Example" functions instead of "Test" functions. This change gives more clarity.
Thats how its written in https://go.dev/blog/examples

Update documentation examples to use 'Example' instead of 'Test' functions

---

.github/workflows/go.yml

In my previous PR I bumped the version of go to 1.22. I forgot to do that in the CI, sorry about that. This PR should fix that.

fix: Update go to 1.22 in CI tests

---

.github/workflows/go.yml

This PR bumps GitHub workflow actions to their latest versions, thus avoiding deprecation warnings as seen e.g. [here](https://github.com/quii/learn-go-with-tests/actions/runs/10013103638).

Bump GitHub actions to their latest versions

---

maps.md
maps/v6/dictionary.go
maps/v7/dictionary.go
maps/v7/dictionary_test.go

In this PR I expanded on the `Delete` method in the maps chapter to be consistent with other CRUD operations in the case that the word being deleted does not exist. The same `Update` switch structure is used to capture errors with a minor change `ErrWordDoesNotExist` to make it applicable to both update and delete operations.

Expanding on maps delete to make it more consistent with add and update

---

context.md

One sentence mentions renaming a struct for clarity, but the struct has had the same name throughout the page.
Another sentence references the `Store` interface where it should be referencing the `Cancel()` method of the interface.

Fix Typos in Context

---

dependency-injection.md

Description:
At this point, Greet func would've been implemented & would output the following error message instead!

Fixed error message in Dependency Injection Chapter

---

iteration.md

To address issue #694, I added a note warning that Go can sometimes optimize functions being benchmarked, leading to inaccurate results. From research this issue seems to be rare, but it is  probably still a good idea to warn users about it. There are several related issues in the Go repository, and people are looking for guidance from the Go team. I believe a warning is sufficient for now, as the benchmarks in the lesson follow the same practices as those in the Go documentation and most other codebases. However, this may need to be revisited in the future if best practices change. I linked a blog post from [Dave Cheney](https://dave.cheney.net/) in the warning so that people could read more and see how to address this issue if it comes up for them.

Add note on potential go benchmark optimisations 

---

generics.md
generics/generics_test.go
generics/stack.go

For issue #770
As an example of how to specify types when calling a function with a generic type that cannot be inferred, added a constructor for `Stack[T]` to Generics chapter. Added to text and code.

Add example of calling generic constructor with type that cannot be inferred

---

.gitignore
build.books.sh
meta.tmpl.tex

Related to [!835](https://github.com/quii/learn-go-with-tests/issues/835).
Tested locally and in GH Actions on my fork.

Possible solution to set the correct version in the PDF footer

---

build.books.sh

This separator avoids conflicts with symbols like `/` in branch names.

Use a safer sed separator in build script to avoid conflicts

---

for/v3/repeat.go
for/v3/repeat_test.go
iteration.md
roman-numerals.md

Relates to https://github.com/quii/learn-go-with-tests/issues/769
The idea is to catch two birds with a stone by showing:
* how useful benchmarks are in evaluating program performance
* how `strings.Builder` can be used to speed up strings concatenation

Add strings.Builder example in for's benchmark section

---

README.md
gb-readme.md

I put this translation above the incomplete ones in the list. If there's anything wrong with it, I'm open to discussion.
**Gitbook** : [Apprendre Go par les Tests](https://goosegeesejeez.gitbook.io/apprendre-go-par-les-tests)
**Repo** : [learn-go-with-tests-fr](https://github.com/GooseGeeseJeez/learn-go-with-tests-fr) - branch `traduction-français`

Complete French translation : adding links to READMEs

---

blogrenderer/renderer_test.go
concurrency.md
concurrency/v1/check_websites_benchmark_test.go
concurrency/v2/check_websites_benchmark_test.go
concurrency/v3/check_websites_benchmark_test.go
for/vx/repeat_test.go
html-templates.md
iteration.md

Replace b.Loop()   with for i:= 0; i< b.N; i++  syntax in 
- blogrenderer/renderer_test.go
- concurrency/v1/check_websites_benchmark_test.go
- concurrency/v2/check_websites_benchmark_test.go  
- concurrency/v3/check_websites_benchmark_test.go
- for/vx/repeat_test.go
- concurrency.md
- html-templates.md (2 instances)
- iteration.md (2 instances)
Verified with `./build.sh` - all tests pass
Fixes #869

Replace b.Loop() with correct benchmark loop syntax in Go
