quii/learn-go-with-tests

for/readme.md
=> change kewords to keywords

hello-world/readme.md
Hi @quii,
Quick one to correct capitalization. Thanks for doing this! Really neat idea.
=> fix capitalization of t.Errorf

arrays/readme.md, arrays/v1/sum.go, arrays/v2/sum.go, arrays/v3/sum.go, arrays/v4/sum.go, arrays/v5/sum.go, arrays/v6/sum.go, arrays/v7/sum.go, for/readme.md, for/v1/repeat.go, for/v2/repeat.go, for/vx/repeat.go, integers/readme.md, integers/v1/adder.go, integers/v2/adder.go, structs/readme.md, structs/v1/shapes.go, structs/v2/shapes.go, structs/v3/shapes.go, structs/v4/shapes.go, structs/v5/shapes.go, structs/v6/shapes.go, structs/v7/shapes.go
=> Use plain return type instead of named result parameter

integers/readme.md
Minor textual clarifications for some of the introduced concepts.
=> minor clarifications for integers

for/readme.md
Minor updates to the iteration section
=> additional clarifications on the content

hello-world.md
Fixed some typos in Chapter 2: Hello, world.
=> Changed some paragraph order and fixed some typos

http-server.md
Would you prefer it if I group these little corrections into a single PR or am I okay to fix them as I find them?
=> Fix code example

http-server.md
Since `GetPlayerScore(name string) int`
=> Fix check for zero value

arrays-and-slices.md
This should resolve issue #60.
=> Add package main and import testing to Array and Slice chapter

http-server.md
A few edits for the http server doc
=> Http server

arrays-and-slices.md
I created this PR from github directly, I think you can use squash and merge as I created two commits instead of one, as it turned out I can use the file name directly without the whole path.
=> Fix for.md link

pointers-and-errors.md
Hi,
unfortunately I have a different ident configuration on my system as the file, so there was a little ... mess :) Thanks to @pityonline for making me aware. This PR should fix the file again.
Chéers!
=> Indent formatting for Pointers & error section

mocking.md, mocking/v3/main.go, mocking/v4/main.go, mocking/v5/countdown_test.go, mocking/v5/main.go
@quii I would love a quick review before I update all the implementation versions in the repo. I am guessing we also need a new `v5` folder added.
Feel free to modify the language however you see fit. I tried to stay with the spirit of the rest of the book.
Resolves #66
=> Sleeper tests

concurrency.md
The new code is from https://github.com/quii/learn-go-with-tests/blob/master/concurrency/v1/CheckWebsites_test.go#L15 .
Fix #80
=> #80 Fix "unnecessary test codes in concurrency.md"

README.md, gb-readme.md
Hi, @quii The Chinese translation is online now! I add the link of Gitbook, please take a look.
=> add Chinese translation link for online reading

maps.md
And thanks for the great read!
=> Fix some typos in maps chapter

hello-world.md, install-go.md, iteration.md
I think the 'New Things' change might be contentious. Visually, I had trouble distinguishing the outline 'unit' from normal bold bits, so i played around with how to break this out as a unit. If it's not liked, happy to revert.
=> Minor Typos and Formatting

io.md
actually,there's no error returning here
=> actually,there's no error returning here

http-server.md
@polaris1119 thanks for pointing this.
=> fix a mistake

maps.md
@hackeryarn When I was proofreading studygolang#26, I also checked the original content. I found that it's good to keep line length less than 80 in codes, but it doesn't look so good in documents. Some sentences are not cut properly, and it's not friendly for translation tools, long URLs, either for some necessary updates in the future. So I joined the separated lines to make it more maintainable. Please have a look. Thanks! cc @quii
=> join separated lines, fix a few small issues

hello-world.md
I have nothing more to add. I just want to thank you all for creating this awesome resource for learning Go and TDD!
=> Fix typo and test text

maps.md
@hackeryarn @quii I found that there's no `Create` in maps chapter, so I changed them to `Add`. Also, I add some sentences to make the context coherent. Please take a look.
=> Update maps chapter

arrays-and-slices.md
Tell me if there's something you want me to change back.
=> Fix typos and other small things

README.md, contributing.md
Not immediately clear where to go to contribute so adding links to make that obvious.
=> add links to contribute

README.md, SUMMARY.md, gb-readme.md, title.txt, websockets.md
Fixing title capitalization throughout the book. This can be verified through sources such as https://capitalizemytitle.com/
=> fixing title capitalization

hello-world.md
add link to "Go Environment" section for easy navigation
=> add link to prev chapter

hello-world.md
Switched "Hola" and "Hello" in error message as is backwards.
=> Update to correct ln 358 error msg

arrays-and-slices.md, hello-world.md
I was approximately 4 chapters in before source control was mentioned. I moved the verbiage from `arrays-and-slices.md` to `hello-world.md` so the reader can be introduced to the concept a bit earlier (especially since we use a github directory when setting up our go structure). Please let me know your thoughts!
=> moved source control verbiage

structs-methods-and-interfaces.md
While going through I thought I had missed where `hasArea` comes from and the introduction of names for the test cases.
Trying to make that more clear with this PR...
=> A few small updates for the last "output" section of " Structs, methods & interfaces"

mocking.md, mocking/v4/countdown_test.go, mocking/v5/countdown_test.go
the instructions were inconsistent with tests and code
=> fix after/before in mocking

context.md, context/v1/context.go, context/v1/context_test.go, context/v2/context.go, context/v2/context_test.go, context/v2/testdoubles.go, context/v3/context.go, context/v3/context_test.go, context/v3/testdoubles.go
fix code and md being out of sync, and context packages being all called v1
=> Context fix

hello-world.md, hello-world/v4/hello.go, hello-world/v5/hello.go, hello-world/v6/hello.go, hello-world/v7/hello.go, hello-world/v8/hello.go
=> Fix english hello prefix const

roman-numerals.md
Hi quii! 😁
I made some suggestions to the roman branch draft for you to take a look at.  🐈
nb, I noticed in the last few code examples you're using a single quote string `'I'` instead of a double quote string `"I"` but I didn't want to change this without running the code first.
=> Add a few grammatical improvements

roman-numerals.md
Also removed some trailing spaces (automatically)
=> Remove 'M' as 'subtractor' and add missing 'I'

roman-numerals.md
=> make my note seem less wanky. maybe

roman-numerals.md
=> Out to our

math.md
Just a few minor typos I spotted whilst going through the chapter
=> fix minor typos on the Maths chapter

io.md
Small fix to the `leagueHandler` function in the `The code so far` section under `IO and sorting`.
=> Fix leagueHandler in IO and sorting The code so far

context.md, error-types.md, io.md, io/v8/FileSystemStore_test.go, io/v9/FileSystemStore_test.go, mocking.md, os-exec.md, pointers-and-errors.md, pointers/v3/wallet_test.go, pointers/v4/wallet_test.go, q-and-a/error-types/error-types_test.go, reflection.md, reflection/v8/reflection_test.go, roman-numerals.md, roman-numerals/v4/numeral_test.go, roman-numerals/v5/numeral_test.go, roman-numerals/v6/numeral_test.go, roman-numerals/v7/numeral_test.go, roman-numerals/v8/numeral_test.go, sync.md, time.md, time/v1/FileSystemStore_test.go, time/v2/FileSystemStore_test.go, time/v3/FileSystemStore_test.go, websockets.md, websockets/v1/FileSystemStore_test.go, websockets/v2/FileSystemStore_test.go, why.md
Replaced all cant, dont, wont, didnt -> can't, don't, won't, didn't
=> Fixed common contractions typing

go.mod, go.sum, structs-methods-and-interfaces.md, structs/v4/shapes_test.go, structs/v5/shapes_test.go, structs/v6/shapes_test.go, structs/v7/shapes_test.go, structs/v8/shapes_test.go
Replaced `%.2f` with`%g`, added a short description and a link to more information
=> Float string format to precision decimal #237

mocking.md
Hello,
I want to thank you for your great effort. I found a typo when coding the example in this tutorial. I fixed this typo according to the source code of this tutorial
=> fixes typo

http-server/v5/InMemoryPlayerStore.go
=> Add mutex to avoid concurrent map read/write error

.travis.yml, go.mod, go.sum, install-go.md
Upgrade golang to the latest v1.13.1. :)
=> Upgrade golang to v1.13.1

roman-numerals.md
I'll describe with inline comments.
=> Minor tweaks to Roman numerals

select.md, select/v2/racer.go, select/v3/racer.go
=> select: change to empty struct and close

http-server/v2/server_test.go, http-server/v3/server_test.go, http-server/v4/server_test.go, http-server/v5/server_test.go
Improve tests in http-server to table driven tests to make test cases more readable.
=> Refactor tests in http-server for readability

time.md
=> Little code fixes on Time tutorial

context.md, math.md, reflection.md, websockets.md
While reading the book, I found that some chapters don't have links to code in this repository. I think there should be those links for consistency.
=> Add links to code to some chapters

structs-methods-and-interfaces.md
=> Fixed typo

maps.md
This is an issue I had while completing the tutorial. I'm no savant of Go, so I might've missed something here.
=> Change assertError in maps section

concurrency.md
=> Fix typo in concurrency.md

math.md
In this example should be %f format to get the error exactly like further in the text
=> Float formatting

websockets.md, websockets/v1/server.go, websockets/v2/server.go
in websockets the magic string for the html template was not fully extracted.
fix #316
=> update refactor htmlTemplatePath

contributing.md
Does it make sense to have this link to issues?
=> Update link to issues

maps.md
2235 - 2245 Fixed typo in Maps documentation (0.17)
=> Fixed typo errors

install-go.md, reflection.md
=> Oof, some PRs on master that should be on main

gb-readme.md, http-server.md, mocking.md
Let me know if you believe these would be helpful edits. 
The main trouble I ran into with this section of the book was where to create files and which files to update where. I was going to add specific file and directory creation into the text when relevant (ass seen with the first commit). For changes and refactors to files, I was planning to add comments to the top of changed code snippets: 
```go
//file.go
package main
...
```
=> (WIP) HTTP chapter edits

mocking.md
I think there is a word missing here as it read a bit funny
=> Fixes grammar in sentence about auto-generating mocks

structs-methods-and-interfaces.md
Corrected a typo on a possessive pronoun in the 2nd to last paragraph of the "Structs, methods & interfaces" page.
PS I've been through many golang guides and this one is the one that clicked for me. Thank you!
=> possessive pronoun

anti-patterns.md
Some suggestions I think makes this chapter easier to read/understand.
=> Little copy edit

anti-patterns.md
Thanks @ruthmoog for editing
Thanks to @shinyhappydan and @gypsydave5 for thoughts and ideas around this topic
=> Anti patterns

context.md
corrected a possessive pronoun by removing a single quotation mark
=> possesive pronoun

time.md
Thank you for the great learning resource on Go. I noticed a small typo and have submitted a fix.
=> Fix PlayPoker typo in time chapter

mocking.md
no longer taking -> no longer take
=> Slight grammar fix

intro-to-generics.md
Question - ln366: should we link to info about slice data type, like with stack?
=> Little copy edit!

iteration.md
|Before|After|
|------|------|
| <img width="629" alt="CleanShot 2021-03-13 at 13 13 53@2x" src="https://user-images.githubusercontent.com/1000669/111018749-08f2e500-83fe-11eb-821d-490a650b433d.png">| <img width="623" alt="CleanShot 2021-03-13 at 13 14 11@2x" src="https://user-images.githubusercontent.com/1000669/111018757-0d1f0280-83fe-11eb-95ea-6ddd01ce0b96.png"> |
=> Fix indentation in refactor section of iteration chapter

dependency-injection.md
type Buffer instead of buffer in dependency-injection.md
=> type Buffer instead of buffer in dependency-injection.md

arrays-and-slices.md, dependency-injection.md, hello-world.md, http-server.md, integers.md, maps.md, pointers-and-errors.md, structs-methods-and-interfaces.md
Hey everyone! 👋  Just wanted to preface this with the fact I'm getting so much value out of this - really fantastic resource!
This PR contains some minor amendments I feel would have improved my understanding as I followed the tutorials.
Things like removing an extra char in an example, rewording some of the lengthier sentences and keeping tenses consistent to improve how some sentences read.
- Fixed [rogue parenthesis](https://github.com/quii/learn-go-with-tests/pull/461/files#diff-46dbb8fc8f2f62f02d43f7be721f173eb9ee2308dd08b8c9e3162109f06062e3L220) in refactored map example
- Split wordier [sentences](https://github.com/quii/learn-go-with-tests/pull/461/files#diff-a70fdf2a914c72f660fff3de45b83704ce07a58533f4976c4fc0e0939697b7daR42-R43) apart
- Reworded some examples …
=> Documentation Tweaks

command-line/v1/server.go, command-line/v2/server.go, command-line/v3/server.go, io.md, io/v1/server.go, io/v2/server.go, io/v3/server.go, io/v4/server.go, io/v5/server.go, io/v6/server.go, io/v7/server.go, io/v8/server.go, io/v9/server.go, json.md, json/v1/server.go, json/v2/server.go, json/v3/server.go, json/v4/server.go, json/v5/server.go, json/v6/server.go, time/v1/server.go, time/v2/server.go, time/v3/server.go, websockets/v1/server.go, websockets/v2/server.go
This was changed with #283 in the previous chapter. Following through with this change in the following chapters to stay consistent.
=> Adapt player name extraction

math.md
A few minor changes which make it easier to understand where to change code, etc.
=> Fix typos and made some code consistent

reading-files.md
=> copy-editing

dependency-injection.md
Not sure if this fits in with the tone of the rest of the text, but I feel the reader may not know where the author got the answer to the question.
Since this reads like it is for beginners, I assume that this is an appropreate assumption.
Please advise,
Nicole
=> Show the reader where to answer similar questions

.github/workflows/go.yml, build.sh
Check the configuration to make sure it is what you want. I have it set to run on all pull requests and pushes to the main branch.
Tested on my fork, it should run first time with no problems. Link to my last run.
https://github.com/wobbol/learn-go-with-tests/runs/3213853213?check_suite_focus=true
=> Create github action for ./build.sh and ./build.books.sh

hello-world.md
As per Mat Ryer's talk about Idiomatic Go code https://youtu.be/yeetIgNeIkc?t=140
And Dave Chaney's post at https://dave.cheney.net/practical-go/presentations/qcon-china.html
> Use blank lines to break up the flow of a function in the same way you use paragraphs to break up the flow of a document. In AverageAge we have three operations occurring in sequence. The first is the precondition, checking that we don’t divide by zero if people is empty, the second is the accumulation of the sum and count, and the final is the computation of the average.
=> Rework the spacing in the examples

README.md, gb-readme.md
Before anything else, thanks for this awesome, mind-blowing resource. It really helps to understand TDD and refactoring, not just Go.
I just started to translate this to Turkish. I want to add the link into the README.md to get help from the Turkish people before finish it up.
=> Update READMEs to add Turkish translation link

json.md
Filename [in_memory_player_store.go](https://github.com/quii/learn-go-with-tests/blob/main/json/v1/in_memory_player_store.go) is snake case.
=> Update file name in comment in json.md

http-handlers-revisited.md
Closing parenthesis seems to be missing.
=> Close parenthesis in http-handlers-revisited.md

http-server.md
For clarity added the package and import lines for this new file. Saves the reader looking it up if unsure or if their IDE doesn't support import autocompletion.
=> New file context: adding package and imports

dependency-injection.md
=> markdown formatting fix

dependency-injection.md
=> Fixed a broken structs link.

concurrency.md
Proposing a quick typo/grammar fix here.
=> Quick typo fix in Concurrency chapter

reading-files.md
=> fix missing brackets

reading-files.md
some code blocks miss highlight
=> fix missing code highlight

app-intro.md
Added websockets section to the `app-intro.md` sections list
=> Add websockets section to app-intro.md

reflection.md, reflection/v1/reflection_test.go, reflection/v10/reflection_test.go, reflection/v2/reflection_test.go, reflection/v3/reflection_test.go, reflection/v4/reflection_test.go, reflection/v5/reflection_test.go, reflection/v6/reflection_test.go, reflection/v7/reflection_test.go, reflection/v8/reflection_test.go, reflection/v9/reflection_test.go
Continuation of PR https://github.com/quii/learn-go-with-tests/pull/550 for the "Reflection" chapter.
=> Fixed capitalization of subtest names

mocking.md
Thanks for putting together this great resource!
Tests still pass after changes:
```console
$ ./build.sh 
ok      github.com/quii/learn-go-with-tests/arrays/v1   (cached)
ok      github.com/quii/learn-go-with-tests/arrays/v2   (cached)
ok      github.com/quii/learn-go-with-tests/arrays/v3   (cached)
ok      github.com/quii/learn-go-with-tests/arrays/v4   (cached)
ok      github.com/quii/learn-go-with-tests/arrays/v5   (cached)
ok      github.com/quii/learn-go-with-tests/arrays/v6   (cached)
ok      github.com/quii/learn-go-with-tests/arrays/v7   (cached)
ok      github.com/quii/learn-go-with-tests/arrays/v8   (cached)
ok      github.com/quii/learn-go-with-tests/blogrenderer        (cached)
ok      github.com/quii/learn-go-with-tests/command-line/v1     (cached)
? …
```
=> Fix small typo in Mocking chapter

intro-to-acceptance-tests.md
Added file specifications to code examples;
Added helper function that was missing from code example;
Fixed any spelling errors;
Made commas and unordered lists consistent;
Refactored sentences for clarity;
=> Fix: Edits to intro-to-acceptance-tests.md

io.md, maps.md, reading-files.md, revisiting-arrays-and-slices-with-generics.md
Hi,
Go code block in markdown have some space indentation.
=> fix space indent

mocking.md
Adds a reference to the original name of Dependency Injection - DI - abbreviation.
=> Adds a reference to the original name of DI

concurrency.md, select.md
👋 Hi @quii - Similar to PR #628, this PR introduces a few grammar and language tweaks that seek to improve readability and consistency. Do these changes seem reasonable?
Thanks!
=> Concurrency & Select grammary/language tweaks

arrays-and-slices.md
The text has been replaced accordingly to #613 
Before the fix:
After the fix:
=> issue #613 fix

math.md
The old website is offline since March 2022.
=> Fix link for XML converter

README.md
Hi, thanks for your awesome learning materials!
I feel that chapter title `Why` should be more clearly in `README.md` Table of contents.
So I updated with full chapter title. Do you like it? 😃 
Thank you.
=> Make chapter title clear in Table of contents

integers.md
The project directory description was confusing. I've changed the wording and added a diagram of a project at this point.
=> Add example file tree

intro-to-acceptance-tests.md
The package name should be mypkg rather than mypg to correspond to mypkg_test
=> Fix package name

math.md
explicitly renames the acceptance tests and adds the new test file with the old file name
=> Clarify that we're creating a new test file for inner loop tests

io.md
Change type from []Player to League so the compared slices are from the same type.
=> Minor bugfix

http-server/v1/server.go
Message return 20 for all requests instead of Hello, World
=> Corrected Message

README.md
i add link to persian translation. it's not complete yet but we are working on it to complete it
=> add persian

contributing.md, install-go.md, integers.md, structs-methods-and-interfaces.md, sync.md
The go wiki link moved away from github.
=> Update go wiki link

reflection.md
related to https://github.com/quii/learn-go-with-tests/issues/736
=> update: simplify the loop with val.Recv()

intro-to-acceptance-tests.md
=> fix: reformat the code in the markdown files

scaling-acceptance-tests.md
Just a tiny patch that might avoid some confusion.
=> fix: directory tree to avoid confusion

integers.md
For correctness:
1. Added a comma
2. Removed an extra incorrect comma in another sentence
=> Fix punctuation in integers.md

intro-to-acceptance-tests.md
I hope this was added by mistake in the code '>'. So, I have removed it.
=> remove '>' from the code 

mocking.md
Fix code to make statement below (`If you run your tests they should still be passing even though the implementation is wrong.`) correct.
=> Fix code in mocking chapter

structs-methods-and-interfaces.md
Clarify which file to create the struct in.
=> Structs: Clarify where to create a struct.

mocking.md, mocking/v5/countdown_test.go, mocking/v6/countdown_test.go
=> fix: change SpyTime receiver function name from Sleep to SetDurationSlept
